package org.popkit.leap.wechart.mapper;

import org.popkit.leap.wechart.entity.Records;

public interface RecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    int insert(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    int insertSelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    Records selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    int updateByPrimaryKeySelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    int updateByPrimaryKey(Records record);
}