package org.popkit.leap.geekpen.entity;

import java.util.Date;

public class Records {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.id
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.openid
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.bookName
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.type
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.updateTime
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private Date updateTime = new Date();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.recordTime
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.isDeleted
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private Integer isDeleted = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.progress
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private Integer progress = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.note
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.id
     *
     * @return the value of Records.id
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.id
     *
     * @param id the value for Records.id
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.openid
     *
     * @return the value of Records.openid
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.openid
     *
     * @param openid the value for Records.openid
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.bookName
     *
     * @return the value of Records.bookName
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.bookName
     *
     * @param bookName the value for Records.bookName
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.type
     *
     * @return the value of Records.type
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.type
     *
     * @param type the value for Records.type
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.updateTime
     *
     * @return the value of Records.updateTime
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.updateTime
     *
     * @param updateTime the value for Records.updateTime
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.recordTime
     *
     * @return the value of Records.recordTime
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.recordTime
     *
     * @param recordTime the value for Records.recordTime
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.isDeleted
     *
     * @return the value of Records.isDeleted
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.isDeleted
     *
     * @param isDeleted the value for Records.isDeleted
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.progress
     *
     * @return the value of Records.progress
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.progress
     *
     * @param progress the value for Records.progress
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.note
     *
     * @return the value of Records.note
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.note
     *
     * @param note the value for Records.note
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}