package org.popkit.leap.geekpen.entity;

import java.util.Date;

public class Records {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.id
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.openid
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.bookName
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.type
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.updateTime
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.createTime
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Records.isDeleted
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.id
     *
     * @return the value of Records.id
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.id
     *
     * @param id the value for Records.id
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.openid
     *
     * @return the value of Records.openid
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.openid
     *
     * @param openid the value for Records.openid
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.bookName
     *
     * @return the value of Records.bookName
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.bookName
     *
     * @param bookName the value for Records.bookName
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.type
     *
     * @return the value of Records.type
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.type
     *
     * @param type the value for Records.type
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.updateTime
     *
     * @return the value of Records.updateTime
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.updateTime
     *
     * @param updateTime the value for Records.updateTime
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.createTime
     *
     * @return the value of Records.createTime
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.createTime
     *
     * @param createTime the value for Records.createTime
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Records.isDeleted
     *
     * @return the value of Records.isDeleted
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Records.isDeleted
     *
     * @param isDeleted the value for Records.isDeleted
     *
     * @mbggenerated Mon Feb 26 20:30:50 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}