package org.popkit.leap.geekpen.entity;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.id
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.openid
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.userName
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.avatar
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.updateTime
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.createTime
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.isDeleted
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.id
     *
     * @return the value of Users.id
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.id
     *
     * @param id the value for Users.id
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.openid
     *
     * @return the value of Users.openid
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.openid
     *
     * @param openid the value for Users.openid
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.userName
     *
     * @return the value of Users.userName
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.userName
     *
     * @param userName the value for Users.userName
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.avatar
     *
     * @return the value of Users.avatar
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.avatar
     *
     * @param avatar the value for Users.avatar
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.updateTime
     *
     * @return the value of Users.updateTime
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.updateTime
     *
     * @param updateTime the value for Users.updateTime
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.createTime
     *
     * @return the value of Users.createTime
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.createTime
     *
     * @param createTime the value for Users.createTime
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.isDeleted
     *
     * @return the value of Users.isDeleted
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.isDeleted
     *
     * @param isDeleted the value for Users.isDeleted
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}