package org.popkit.leap.geekpen.mapper;

import org.apache.ibatis.annotations.Param;
import org.popkit.leap.geekpen.entity.Records;

import java.util.List;
import java.util.Date;

public interface RecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    int insert(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    int insertSelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    Records selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    int updateByPrimaryKeySelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Thu Mar 01 20:18:41 CST 2018
     */
    int updateByPrimaryKey(Records record);

    List<Records> queryLatest(Integer limit);

    List<Records> queryRecords(String openid);

    List<Records> queryDatasFromTime(@Param(value = "openid") String openid, @Param(value = "beginTime") Date beginTime);

}