package org.popkit.leap.geekpen.mapper;

import org.apache.ibatis.annotations.Param;
import org.popkit.leap.geekpen.entity.Records;

import java.util.List;
import java.util.Date;

public interface RecordsMapper {
    List<Records> queryLatest(Integer limit);

    List<Records> queryDatasFromTime(@Param(value = "openid") String openid, @Param(value = "beginTime") Date beginTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Wed Feb 28 20:14:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Wed Feb 28 20:14:01 CST 2018
     */
    int insert(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Wed Feb 28 20:14:01 CST 2018
     */
    int insertSelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Wed Feb 28 20:14:01 CST 2018
     */
    Records selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Wed Feb 28 20:14:01 CST 2018
     */
    int updateByPrimaryKeySelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Records
     *
     * @mbggenerated Wed Feb 28 20:14:01 CST 2018
     */
    int updateByPrimaryKey(Records record);
}