package org.popkit.leap.geekpen.mapper;

import org.popkit.leap.geekpen.entity.Users;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbggenerated Wed Feb 28 20:15:18 CST 2018
     */
    int updateByPrimaryKey(Users record);
}